add a lint-results step

diff --git a/.github/workflows/lint-test.yaml b/.github/workflows/lint-test.yaml
--- a/.github/workflows/lint-test.yaml
+++ b/.github/workflows/lint-test.yaml
@@ -10,6 +10,7 @@ jobs:
   lint-test:
     runs-on: ubuntu-22.04
     strategy:
+      fail-fast: false
       matrix:
         # Supported versions at https://kubernetes.io/releases/
         version:
@@ -50,3 +51,17 @@ jobs:
 
       - name: Run chart-testing (install)
         run: ct install --config ct.yaml
+
+  lint-results:
+    if: always()
+    needs: [ lint-test ]
+    runs-on: ubuntu-22.04
+    steps:
+      - run: |
+          result="${{ needs.lint-test.result }}"
+          if [[ "$result" == "success" || "$result" == "skipped" ]]; then
+            echo "All charts passed linting and tests"
+          else
+            echo "One or more charts failed linting or tests" >&2
+            exit 1
+          fi
